import commands as cmd
from output import Message
admin_dispatch = {
    'a': cmd.cmd_add,
    'add': cmd.cmd_add,
    'f': cmd.cmd_edit,
    'full': cmd.cmd_edit,
    'g': cmd.cmd_get,
    'get': cmd.cmd_get,
    'h': cmd.cmd_help,
    'help': cmd.cmd_help,
    'i': cmd.cmd_import,
    'import': cmd.cmd_import,
    'ls': cmd.cmd_list,
    'list': cmd.cmd_list,
    'l': cmd.cmd_last,
    'last': cmd.cmd_last,
    's': cmd.cmd_search,
    'search': cmd.cmd_search,

    'n': lambda x: Message("next"),
    'next': lambda x: Message("next"),
    'p': lambda x: Message("prev"),
    'prev': lambda x: Message("prev"),
    'q': lambda x: Message("quit"),
    'quit': lambda x: Message("quit"),
    'today': "_",
    'week': "_",
    'day': "_",
}
